### ISSUE TITLE
Can't get this library to work

### ISSUE THREAD

**Issue by 1TheMuffinMan** [louiealmeda/AzureFunctions.Auth0#1]
After following your instructions and testing the function I get the following error: ` Could not load file or assembly 'Microsoft.IdentityModel.Protocols, Version=6.8.0.0`. I've added that nuget package with that version and I still get the same error.

I downloaded the code, updated all of the nuget packages to the latest and still same issue.

Any idea?

Getting Auth0 set up for Functions is taking longer than actually writing my entire application

**Comment by louiealmeda** [comment]
Hi @1TheMuffinMan, can you try using the `Microsoft.IdentityModel.Protocols.OpenIdConnect 5.6.0` version? And your app should be running with dotnet core 2.1

Try to match the versions here:
https://github.com/louiealmeda/AzureFunctions.Auth0/blob/master/AzureFunctions.Auth0.csproj

**Comment by 1TheMuffinMan** [comment]
Hi, the problem I found is that I am using .net core so I had to use a different open id connect nuget package.
